power = ['good-luck', 'flying', 'dark-power', 'magic']

Creature.create({ name: 'Thomas',
                  type: 'dragon',
                  age: 45,
                  address: '6 rue du dragon,75006 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 49 })
Creature.create({ name: 'Lea',
                  type: 'dragon',
                  age: 32,
                  address: '33 Av. Secrétan, 75019 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 35 })
Creature.create({ name: 'Elio',
                  type: 'dragon',
                  age: 356,
                  address: '32 rue dagorno,75012 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 23 })
Creature.create({ name: 'Winston',
                  type: 'dragon',
                  age: 85,
                  address: '25 rue du dragon,75006 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 154 })
Creature.create({ name: 'Eva',
                  type: 'elf',
                  age: 593,
                  address: '15 Rue Montmartre, 75001 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 95 })
Creature.create({ name: 'Megan',
                  type: 'elf',
                  age: 54,
                  address: '77 Rue de Varenne, 75007 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 76 })
Creature.create({ name: 'Karen',
                  type: 'elf',
                  age: 98,
                  address: '17 Rue Crozatier, 75012 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 30 })
Creature.create({ name: 'David',
                  type: 'elf',
                  age: 100,
                  address: '334 Rue des Pyrénées, 75020 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 84 })
Creature.create({ name: 'Wilfrid',
                  type: 'wizard',
                  age: 76,
                  address: '15 Rue Lepic, 75018 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 60 })
Creature.create({ name: 'Tony',
                  type: 'wizard',
                  age: 46,
                  address: '8 Av. Dutuit, 75008 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 10 })
Creature.create({ name: 'Edmund',
                  type: 'wizard',
                  age: 32,
                  address: '79 Av. Bosquet, 75007 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 203 })
Creature.create({ name: 'Amelia',
                  type: 'demon',
                  age: 90,
                  address: '24 bis Rue de Saint-Pétersbourg, 75008 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 198 })
Creature.create({ name: 'Tom',
                  type: 'demon',
                  age: 666,
                  address: '67 Av. de la Bourdonnais, 75007 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 57 })
Creature.create({ name: 'Sasha',
                  type: 'demon',
                  age: 66,
                  address: '54 Av. Mozart, 75016 Paris',
                  power: power.sample,
                  description: "Hi I'm a super friendly creature and i'd be more than happy for spend time with you",
                  price_per_day: 28 })
